[package]
name = "fpt"
version = "0.1.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
license="MIT"
readme = "README.md"
repository = "https://github.com/gifnksm/fpt"
keywords = ["game"]
description = "First Person Tetris"

[dependencies]
piston_window = "0.80"
rand = "0.5"
time = "0.1"
